services:
  # =========================================================================
  # POSTGRESQL: Source of Truth (SoT) Replica Sync
  # =========================================================================
  postgres_sot:
    image: postgres:15-alpine
    container_name: postgres_burung_sot
    environment:
      POSTGRES_USER: burung_admin
      POSTGRES_PASSWORD: burung_secure_pass
      POSTGRES_DB: burung_sot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - logical_net

  redis:
    image: redis:latest
    container_name: redis_burung_cache
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - logical_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_burung_message_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: burung_user
      RABBITMQ_DEFAULT_PASS: burung_pass
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions_vhost_rmq.json:/etc/rabbitmq/definitions_vhost_rmq.json:ro
    networks:
      - logical_net

  minio:
    image: minio/minio:latest
    container_name: minio_burung_storage
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: burung_app
      MINIO_ROOT_PASSWORD: burung_app123
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Console UI
    volumes:
      - minio_data:/data
    restart: unless-stopped
    networks:
      - logical_net

volumes:
  postgres_data:
  minio_data:

networks:
  logical_net:
    driver: bridge