networks:
  cassandra_net:
    driver: bridge

services:
  redis:
    image: redis:latest
    container_name: redis_burung_cache
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_burung_message_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: burung_user
      RABBITMQ_DEFAULT_PASS: burung_pass
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions_vhost_rmq.json:/etc/rabbitmq/definitions_vhost_rmq.json:ro

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch_burung_search_engine
    environment:
      MEILI_MASTER_KEY: "SuperSecureKey123456"
    ports:
      - "7700:7700"
    restart: unless-stopped

  # =========================================================================
  # CLUSTER 1: burung_historical (Cukup 1 Node untuk Dev)
  # =========================================================================
  historical-node1:
    image: cassandra:4.1
    container_name: cassandra_historical_n1
    networks:
      - cassandra_net
    environment:
      - CASSANDRA_CLUSTER_NAME=burung_historical
      - CASSANDRA_NUM_TOKENS=1
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
    ports:
      - "9042:9042"
    restart: unless-stopped

  # =========================================================================
  # CLUSTER 2: burung_sot_replica (Cukup 1 Node untuk Dev)
  # =========================================================================
  sot-node1:
    image: cassandra:4.1
    container_name: cassandra_sot_n1
    networks:
      - cassandra_net
    environment:
      - CASSANDRA_CLUSTER_NAME=burung_sot_replica
      - CASSANDRA_NUM_TOKENS=1
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
    ports:
      - "9043:9042"
    restart: unless-stopped

  # =========================================================================
  # SISA SERVICE
  # =========================================================================
  minio:
    image: minio/minio:latest
    container_name: minio_burung_storage
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: burung_app
      MINIO_ROOT_PASSWORD: burung_app123
    ports:
      - "9000:9000"   # API S3 compatible
      - "9001:9001"   # MinIO console UI
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  minio_data: